### ISSUE TITLE
Nonce found but not added to Accepted total.

### ISSUE THREAD

**Issue by HONO** [dero-am/astronv#1]
Nonce found but not added to Accepted total.
![Sans-titre-1](https://github.com/dero-am/astronv/assets/486424/df26397a-62a2-40a0-94ba-d89a527343f6)
it was added to my wallet
![image](https://github.com/dero-am/astronv/assets/486424/034a005e-a8ae-4899-a5e4-d5c55cb3bd67)

**Comment by HONO** [comment]
The next one work correctly
![image](https://github.com/dero-am/astronv/assets/486424/1c836ac6-ca8f-4613-889c-557eefcb4e19)

**Comment by dero-am** [comment]
@HONO We have seen this bug for a long time, it's node bug and not related to the miner. The miner JUST shows the stats that it receives from your node. The miner doesn't count your mined block or rejected block.
