### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by HONO** [dero-am/astronv#2]
Memory leak on hive.
Consume ram little by little.
Near 1gb in 5h
astronv 1.0.5 hive 0.6-224@231022
A 21.40.1 (5.13.2208)
N 535.113.01
DRIVERS

**Comment by jonasjlo** [comment]
Here Too! upvote

**Comment by jonasjlo** [comment]
> Memory leak on hive. Consume ram little by little. Near 1gb in 5h astronv 1.0.5 hive 0.6-224@231022 A 21.40.1 (5.13.2208) N 535.113.01 DRIVERS

Did you solve?
